**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

In [13]:
import pandas as pd
data = {'colors': ['red', 'blue', 'green', 'yellow', 'black'],
        'items': ['ball', 'pen', 'pencil', 'eraser', 'sharpener'],
        'price': [2000, 1000, 3000, 5000, 4000]}
frame = pd.DataFrame(data)
frame

   colors      items  price
0     red       ball   2000
1    blue        pen   1000
2   green     pencil   3000
3  yellow     eraser   5000
4   black  sharpener   4000

In [4]:
import pandas as pd
frame2 = pd.DataFrame(data,columns=['object','price'])
frame2

  object  price
0    NaN   2000
1    NaN   1000
2    NaN   3000
3    NaN   5000
4    NaN   4000

In [6]:
frame2 = pd.DataFrame(data, index=['one', 'two', 'three', 'four', 'five'], columns=['object','price'])
frame2

      object  price
one      NaN   2000
two      NaN   1000
three    NaN   3000
four     NaN   5000
five     NaN   4000

In [11]:
import numpy as np
import pandas as pd

frame3 = pd.DataFrame(
    np.arange(16).reshape((4,4)),
    index=['red', 'blue', 'white', 'black'],
    columns=['ball', 'pen', 'pencil', 'scale']
)

print(frame3)

       ball  pen  pencil  scale
red       0    1       2      3
blue      4    5       6      7
white     8    9      10     11
black    12   13      14     15

In [12]:
frame.values

array([['red', 'ball', 2000],
       ['blue', 'pen', 1000],
       ['green', 'pencil', 3000],
       ['yellow', 'eraser', 5000],
       ['black', 'sharpener', 4000]], dtype=object)

In [14]:
frame3.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
frame['price']

0    2000
1    1000
2    3000
3    5000
4    4000
Name: price, dtype: int64

In [19]:
frame3.index

Index(['red', 'blue', 'white', 'black'], dtype='str')

In [20]:
frame3.columns

Index(['ball', 'pen', 'pencil', 'scale'], dtype='str')

In [18]:
frame3.ball

red       0
blue      4
white     8
black    12
Name: ball, dtype: int64

In [16]:
frame3.loc['red']

ball      0
pen       1
pencil    2
scale     3
Name: red, dtype: int64

In [17]:
frame3.iloc[0]

ball      0
pen       1
pencil    2
scale     3
Name: red, dtype: int64

In [21]:
frame3.loc['red','pen']

np.int64(1)

In [25]:
frame3.iloc[0, 1]

np.int64(1)

In [24]:
frame3.iloc[2, 3]

np.int64(11)

In [38]:
frame3.iloc[[2,3],[2,3]]

       pencil  scale
white      10     11
black      14     15

In [42]:
frame3.loc['white' , ['pencil','scale']]

pencil    10
scale     11
Name: white, dtype: int64

In [46]:
frame.index.name = 'id'
frame.columns.name = 'item'
frame

item  colors      items  price
id
0        red       ball   2000
1       blue        pen   1000
2      green     pencil   3000
3     yellow     eraser   5000
4      black  sharpener   4000

In [47]:
frame['new'] = 12
frame

item  colors      items  price  new
id
0        red       ball   2000   12
1       blue        pen   1000   12
2      green     pencil   3000   12
3     yellow     eraser   5000   12
4      black  sharpener   4000   12

In [48]:
frame['new'] = [12,14,85,96,78]
frame

item  colors      items  price  new
id
0        red       ball   2000   12
1       blue        pen   1000   14
2      green     pencil   3000   85
3     yellow     eraser   5000   96
4      black  sharpener   4000   78