**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

Defining a Dataframe

In [2]:
import pandas as pd
data = {'colors': ['red', 'blue', 'green', 'yellow', 'black'],
        'items': ['ball', 'pen', 'pencil', 'eraser', 'sharpener'],
        'price': [2000, 1000, 3000, 5000, 4000]}
frame = pd.DataFrame(data)
frame

   colors      items  price
0     red       ball   2000
1    blue        pen   1000
2   green     pencil   3000
3  yellow     eraser   5000
4   black  sharpener   4000

In [3]:
frame['new'] = 12
frame

   colors      items  price  new
0     red       ball   2000   12
1    blue        pen   1000   12
2   green     pencil   3000   12
3  yellow     eraser   5000   12
4   black  sharpener   4000   12

In [4]:
frame['new'] = [12,14,85,96,78]
frame

   colors      items  price  new
0     red       ball   2000   12
1    blue        pen   1000   14
2   green     pencil   3000   85
3  yellow     eraser   5000   96
4   black  sharpener   4000   78

In [7]:
import numpy as np
ser = pd.Series(np.arange(5))
ser

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [8]:
frame ['new'] = ser
frame

   colors      items  price  new
0     red       ball   2000    0
1    blue        pen   1000    1
2   green     pencil   3000    2
3  yellow     eraser   5000    3
4   black  sharpener   4000    4

Assigning Values

In [13]:
frame['price'][2]=1000
frame

C:\Users\hppc\AppData\Local\Temp\ipykernel_9488\1041182878.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  frame['price'][2]=1000

   colors      items  price  new
0     red       ball   2000    0
1    blue        pen   1000    1
2   green     pencil   3000    2
3  yellow     eraser   5000    3
4   black  sharpener   4000    4

In [14]:
frame.loc[2,'price']=2500
frame

   colors      items  price  new
0     red       ball   2000    0
1    blue        pen   1000    1
2   green     pencil   2500    2
3  yellow     eraser   5000    3
4   black  sharpener   4000    4

Membership of a Value

In [15]:
frame.isin([1.0,'pen'])

   colors  items  price    new
0   False  False  False  False
1   False   True  False   True
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False

In [16]:
frame[frame.isin([1.0,'pen'])]

  colors items  price  new
0    NaN   NaN    NaN  NaN
1    NaN   pen    NaN  1.0
2    NaN   NaN    NaN  NaN
3    NaN   NaN    NaN  NaN
4    NaN   NaN    NaN  NaN

Deleting a Column

In [17]:
del frame['new']
frame

   colors      items  price
0     red       ball   2000
1    blue        pen   1000
2   green     pencil   2500
3  yellow     eraser   5000
4   black  sharpener   4000

 Filtering

In [ ]:
frame[frame < 1.2]
frame

DataFrame from Nested dict

In [22]:
nestdict = { 'red': { 2012: 22, 2013: 33 },
 'white': { 2011: 13, 2012: 22, 2013: 16},
 'blue': {2011: 17, 2012: 27, 2013: 18}}

In [23]:
frame2 = pd.DataFrame(nestdict)
frame2

       red  white  blue
2012  22.0     22    27
2013  33.0     16    18
2011   NaN     13    17

Transposition of a Dataframe

In [24]:
frame2.T

       2012  2013  2011
red    22.0  33.0   NaN
white  22.0  16.0  13.0
blue   27.0  18.0  17.0